version: '3'
services: 
    api:
        image: d2d-backend
        build: ./back-end
        ports:
            - "3000:3000"
        volumes: 
            - ./back-end:/usr/src/app
            - /usr/src/app/node_modules
        depends_on: 
            - mongo
            - redis
        environment: 
            - ENV="production"
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
    adminmongo:
        image: "mrvautin/adminmongo"
        ports:
            - "1234:1234"
        environment: 
            - HOST=0.0.0.0
    redis:
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        ports:
            - "6379:6379"